version: 2.1

jobs:

  workspace:
    docker:
      - image: cimg/base:2022.05
    steps:
      - run:
          name: Create workspace directory
          command: |
            sudo mkdir -p /workspace
            sudo chown -R $USER:$USER /workspace
      - attach_workspace:
          at: /workspace

  cypress-run:
    docker:
      - image: cypress/base:12.18.3
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-
      - save_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Run Cypress tests
          command: |
            npx cypress run
      - store_test_results:
          path: cypress/test-results
      - store_artifacts:
          name: Create screenshots
          path: cypress/screenshots
          destination: screenshots
      - store_artifacts:
          name: Create videos
          path: cypress/videos
          destination: videos
      - store_artifacts:
          name: Create report
          path: /root/project/cypress/reports/html
          destination: report
      - store_artifacts:
          path: cypress/test-results

# create-screenshots:
#   docker:
#     - image: cimg/base:2022.05
#   steps:
#     - attach_workspace:
#         at: /workspace
#     - run:
#         name: Create screenshots
#         command: |
#           mkdir -p cypress/screenshots
#           circleci-agent artifacts download screenshots ./cypress/screenshots

# create-videos:
#   docker:
#     - image: cimg/base:2022.05
#   steps:
#     - attach_workspace:
#         at: /workspace
#     - run:
#         name: Create videos
#         command: |
#           mkdir -p cypress/videos
#           circleci-agent artifacts download videos ./cypress/videos

workflows:
  test:
    jobs:
      - workspace
      - cypress-run:
          requires:
            - workspace
      # - create-screenshots:
      #     requires:
      #       - cypress-run
      # - create-videos:
      #     requires:
      #       - cypress-run
